version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-api-listingec2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-73rspm8u3y6k"
s3_prefix = "lambda-api-listingec2"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
