AWSTemplateFormatVersion: '2010-09-09'
Description: "Static Website using cloudfront and S3"

Parameters:
  S3BucketNameWeb:
    Type: String
    Default: "static-web-hello-world-micro-project"
    MinLength: 3
    MaxLength: 63

Resources:
  S3BucketLogging:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub bucket-${AWS::AccountId}-${AWS::Region}-logging-webapp
      AccessControl: PublicRead
      #VersioningConfiguration:
      #  Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    
# https://aws.amazon.com/premiumsupport/knowledge-center/s3-website-cloudfront-error-403/
  S3BucketWebHelloWorld:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref S3BucketNameWeb
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      
      #VersioningConfiguration:
      #  Status: Enabled

  S3HostingBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3BucketNameWeb
        PolicyDocument:
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: Allow
              Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3BucketNameWeb
                  - /*
              Principal:
                CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

    # Configure CloudFront
  CloudFrontDistributionWebApp:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: "/error.html"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          # TTL very low for testing purpose
          DefaultTTL: 30 # in seconds
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 40 # in seconds
          MinTTL: 20 # in seconds
          TargetOriginId: S3-private-bucket
          ViewerProtocolPolicy: "redirect-to-https"
        # This DefaultRootObject configuration is not enough.
        DefaultRootObject: 'index.html'
        Comment: "CDN for Micro-WebApp"
        Logging: 
          Bucket: !Sub '${S3BucketLogging}.s3.amazonaws.com'
          Prefix: "cloudfront-webapp"
        Enabled: true
        HttpVersion: http2
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Origins:
          - Id: S3-private-bucket
            DomainName: !GetAtt S3BucketWebHelloWorld.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        # less expensive, serve only US, Canada, Mexico, EU and Israel     
        PriceClass: PriceClass_100

  # Cloud Origin Access Identity to only give access to CloudFront to access bucket       
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'origin identity s3 webapp'

Outputs:
  WebSiteUrlWebApp:
    Description: 'URL for website hosted on S3 - to test permission - only access from Origin'
    Value: !GetAtt S3BucketWebHelloWorld.WebsiteURL

  LoggingBucketName:
    Description: 'Name of the bucket for logging'
    Value: !Ref S3BucketLogging

  DomainNameBucket:
    Description: 'Domain Name of the bucket'
    Value: !GetAtt S3BucketWebHelloWorld.DomainName
  
  DomainNameCloudFront:
    Description: 'Domain Name used by CloudFront'
    Value: !GetAtt CloudFrontDistributionWebApp.DomainName