AWSTemplateFormatVersion: 2010-09-09
Description: >
  Create an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. This example creates an EC2 security group
  for the instance to give you SSH access and create a Mysql Instance

Parameters:
  #Parameter for EC2 Instance
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceTypeEC2:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.nano
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium]
    ConstraintDescription: must be a valid EC2 instance type.

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  
  LatestAmiId:
    Type:  'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceTypeEC2'
      SecurityGroups: [!Ref 'InstanceSecurityGroupEC2']
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'
      UserData:
        !Base64 |
          #cloud-config
          write_files:
            - path: test.txt
              content: "97LEDKYGOF6C56Q4GYR"
          yum_repos:
            mariadb:
              baseurl: http://yum.mariadb.org/10.5/centos7-amd64
              gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
              gpgcheck: true
              enabled: true
              name: Package for MariaDB - fork Mysql
          package_update: true
          package_upgrade: true
          package_reboot_if_required: true
          packages:
            - MariaDB-client
      Tags:
        -
          Key: Name
          Value: !Sub '${AWS::StackName}-ec2'

  InstanceSecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref 'SSHLocation'

Outputs:
  InstanceIdEC2:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  AZInstanceIdEC2:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, AvailabilityZone]
  PublicDNSInstanceIdEC2:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicDnsName]
  PublicIPInstanceIdEC2:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]